### ISSUE TITLE
Epic 1: General Site Functionality

### ISSUE THREAD

**Issue by LesterCuasay** [LesterCuasay/productivity-app#1]
As a **role** I can **capability** so that **benefit**

- [ ] As a **first-time site visitor** I can **clearly understand the site's purpose** so that **I can decide whether or not to keep exploring the website**
- [ ] As a **user** I can **easily navigate through the website** so that **I can find the content I am looking for with ease**
- [ ] As a **user** I can **create an account** so that **I can access all the features of the website**
- [ ] As a **user** I can **sign in** so that **I can access the feature for signed in users**
- [ ] As a **user** I can **clearly see that I am logged in** so that **I am aware of my current logged in status**
- [ ] As a **user** I can **be able to navigate the website without being logged out** so that **I have the choice when I am logged out**
- [ ] As a **non-signed up user** I can **visibility see the sign in/sign up options** so that **I can sign in or make an account**
