### ISSUE TITLE
Epic 3: Task Management

### ISSUE THREAD

**Issue by LesterCuasay** [LesterCuasay/productivity-app#14]
- [ ] As a **Site User** I can **add a due date** so that **I can prioritise my tasks**
- [ ] As a **Site User** I can **see which tasks are overdue** so that **I can clearly see what needs doing first**
- [ ] As a **Site User** I can **set priority for a task** so that **I know which tasks are needed to be done in order**
- [ ] As a **Site User** I can **see all my current non-finished tasks** so that **I can decide on what to do first**
- [ ] As a **Site user** I can **move my tasks** so that **it can reflect the current status**
- [ ] As a **Site User** I can **filter my tasks** so that **I can clearly see depending on the filtered option**
