### ISSUE TITLE
Epic 2: Task Creation/Deletion

### ISSUE THREAD

**Issue by LesterCuasay** [LesterCuasay/productivity-app#9]
As a **role** I can **capability** so that **benefit**

- [ ] As a **Site User** I can **add new tasks** so that **I can remind myself on what to do**
- [ ] As a **Site User** I can **edit my tasks** so that **I can change something if I make a mistake**
- [ ] As a **Site User** I can **delete my tasks** so that **I can remove tasks that are not needed anymore**
- [ ] As a **Site User** I can **set a status for my tasks** so that **I know which tasks I am currently doing**
